version: '3'
services:
  harmony-prises:
    container_name: harmony-prises
    image: docker-harmony-prises:latest
    restart: always
    build: .
    ports:
      - "8042:8042"
    command: /root/startup.sh
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    tty: true
